### ISSUE TITLE
catalogue narrative complexity of imsdb scripts

### ISSUE THREAD

**Issue by vassiki** [ContextLab/narrative_complexity#2]
- [x] Create a notebook to load Mark's csv
- [x] Extract the text in a bag of words format
- [x] Tokenize words to prepare for linguistic analysis
- [x] Get sentiments for each words
- [x] Perform part of speech tagging with nltk
- [x] Tag the named entities
- [x] Characterize semantic consistency within windows
- [x] Visualize all this information

**Comment by jeremymanning** [comment]
some other code for doing sentiment analysis: [[link](https://github.com/ContextLab/storytelling-with-data/blob/master/data-stories/twitter-finance/twitter-finance.ipynb)]
