### ISSUE TITLE
start a google slides presentation outlining the main ideas and questions

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/narrative_complexity#20]

**Comment by jeremymanning** [comment]
we can paste in figures and/or analysis ideas and/or results as we go

**Comment by vassiki** [comment]
https://docs.google.com/presentation/d/1pWY2tV-5vg0wTS-ujJM0wq9TBW_hfLN1kz_Bud37cR0/edit?usp=sharing

Everyone has edit access, feel free to change for whatever needs to be changed.
