### ISSUE TITLE
complexity by characters

### ISSUE THREAD

**Issue by vassiki** [ContextLab/narrative_complexity#8]
- [x] Get windows for narrative
- [x] Perform Named Entity Recognition within the window
- [x] For each script, use the number of unique NEs as a proxy for complexity
- [x] Create a character co-occurrence matrix for each script
- [x] Study evolution of social networks of characters
- [x] Identify raw sentiment around NEs, characterize the trajectory of sentiment across
        all windows for each character

**Comment by vassiki** [comment]
Of special interest to @sbrietzke!

**Comment by sbrietzke** [comment]
- [ ] Identify co-occurrence of topics with each character as proxy for character development
